#!/usr/bin/env bash

PDF="$(ls hacking_tools_cheat_sheet_v*.pdf)"
PNG="$(sed 's/\.pdf$/.png/' <<< $PDF)"

convert -background white -alpha remove -alpha off -density 300 "$PDF" "$PNG"
convert -append "$PDF" "$PNG"
